[build]
command = "pip install -r requirements-cloudflare.txt"

[build.upload]
format = "service-worker"

[site]
bucket = "./app"

[env.production]
name = "guardadocs"
workers_dev = true

[env.production.build]
command = "pip install -r requirements-cloudflare.txt && python -m hypercorn app.main:app --bind 0.0.0.0:8000" 