name = "guardadocs-app"
main = "app/worker.js"
compatibility_date = "2024-02-15"

[build]
command = "chmod +x build.sh && ./build.sh"
pages_build_output_dir = "static"
publish = "app"

[build.upload]
format = "service-worker"

[build.environment]
PYTHON_VERSION = "3.11"

[site]
bucket = "./static"
entry-point = "app/main.py"

[env.production]
name = "guardadocs-app"
route = "guardadocs-app.pages.dev/*"
workers_dev = true

[[env.production.services]]
name = "python-app"
command = "python -m hypercorn app.main:app --bind 127.0.0.1:8000"

[[build.process]]
command = "python -m hypercorn app.main:app --bind 127.0.0.1:8000" 