name = "guardadocs-app"
main = "app/worker.js"
compatibility_date = "2024-02-15"

[build]
command = "pip install -r requirements-cloudflare.txt"

[build.upload]
format = "service-worker"

[site]
bucket = "./app"

[env.production]
name = "guardadocs"
workers_dev = true

[[env.production.services]]
name = "python-app"
command = "python -m hypercorn app.main:app --bind 127.0.0.1:8000" 