name = "guardadocs"
type = "javascript"
account_id = "" # Você preencherá isso depois
workers_dev = true
compatibility_date = "2024-02-15"

[site]
bucket = "./public"
entry-point = "workers-site"

[build]
command = "pip install -r requirements-cloudflare.txt"
output_dir = "public"

[env.production]
name = "guardadocs-prod"
route = "guardadocs.yourdomain.com/*"  # Você ajustará isso depois

# Variáveis de ambiente serão configuradas no dashboard do Cloudflare 